default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=600']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    - id: mypy
      name: mypy for granite_core
      args: [--ignore-missing-imports, --python-executable, granite_core/.venv/bin/python]
      files: granite_core
    - id: mypy
      name: mypy for acp
      args: [--ignore-missing-imports, --python-executable, acp/.venv/bin/python]
      files: acp
    - id: mypy
      name: mypy for a2a
      args: [--ignore-missing-imports, --python-executable, a2a/.venv/bin/python]
      files: a2a
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: gitlint
        language: python
        entry: gitlint
        args: [--staged, --msg-filename]
        stages: [commit-msg]
  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.64.dss
    hooks:
      - id: detect-secrets
        additional_dependencies:
        - boxsdk~=3.0
        args: [--baseline, .secrets.baseline, --use-all-plugins, --fail-on-unaudited]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.0
    hooks:
      - id: uv-lock
        name: uv lock granite core
        files: granite_core/pyproject.toml
        args: [--directory, granite_core]
      - id: uv-lock
        name: uv lock acp
        files: acp/pyproject.toml
        args: [--directory, acp]
      - id: uv-lock
        name: uv lock a2a
        files: a2a/pyproject.toml
        args: [--directory, a2a]
