[project]
name = "granite-chat"
version = "0.1.0"
description = "ACP Granite Chat"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "acp-sdk>=0.8.4",
    "beeai-framework>=0.1.21",
    "python-dotenv>=1.1.0",
]
