[project]
name = "mcp_services"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.25.0",
    "granite-core",
]

[tool.uv.sources]
granite-core = { path = "../granite_core", editable = true }